pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
      - refs/heads/*
      - refs/tags/*

steps:
- task: CmdLine@2
  displayName: shellcheck
  inputs:
    script: find . -type f -name '*.sh' | xargs shellcheck

- template: .azure-pipelines/docker.yml
  parameters:
    images:
    - cockroachdb
    - mysql