parameters:
  images: []

steps:
- ${{ each image in parameters.images }}:
  - task: CmdLine@2
    displayName: Build ${{ image }} image
    inputs:
      script: docker build -t shawntoffel/backup:${{ image }}-$(Build.SourceBranchName) ${{ image }}

  - task: Docker@2
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'refs/tags/${{ image }}'))
    displayName: Docker push
    inputs:
      containerRegistry: dockerhub
      command: push
      repository: shawntoffel/backup
      tags: ${{ image }}-$(Build.SourceBranchName)